version: '2'
services: 
  zookeeper:
    image: wurstmeister/zookeeper          
    ports: 
      - "2181:2181"
  kafka: 
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.100.141
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  cron: 
    build: ./sensor-cron
    volumes:
      - ./log:/var/log
  fluentd: 
    build: .
    ports: 
      - "8889:8889"
    volumes:
      - ./log:/var/log
    depends_on:
      - kafka
